# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('sec', models.CharField(max_length=10)),
            ],
        ),
    ]
